language: php

php:
  - 5.3
  - 5.4

env:
  # - SYMFONY_VERSION=2.1.x-dev
  - SYMFONY_VERSION=origin/master

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit --coverage-text