language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.1.3
  - SYMFONY_VERSION=origin/master

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit --coverage-text