<?php
namespace Codemitte\Sfdc\Soap\Mapping\Type;

class ExceptionCode extends GenericType
{
    const API_CURRENTLY_DISABLED = 'API_CURRENTLY_DISABLED';

    const API_DISABLED_FOR_ORG = 'API_DISABLED_FOR_ORG';

    const ARGUMENT_OBJECT_PARSE_ERROR = 'ARGUMENT_OBJECT_PARSE_ERROR';

    const CANNOT_DELETE_OWNER = 'CANNOT_DELETE_OWNER';

    const CANT_ADD_STANDADRD_PORTAL_USER_TO_TERRITORY = 'CANT_ADD_STANDADRD_PORTAL_USER_TO_TERRITORY';

    const CANT_ADD_STANDARD_PORTAL_USER_TO_TERRITORY = 'CANT_ADD_STANDARD_PORTAL_USER_TO_TERRITORY';

    const CIRCULAR_OBJECT_GRAPH = 'CIRCULAR_OBJECT_GRAPH';

    const CLIENT_NOT_ACCESSIBLE_FOR_USER = 'CLIENT_NOT_ACCESSIBLE_FOR_USER';

    const CLIENT_REQUIRE_UPDATE_FOR_USER = 'CLIENT_REQUIRE_UPDATE_FOR_USER';

    const CUSTOM_METADATA_LIMIT_EXCEEDED = 'CUSTOM_METADATA_LIMIT_EXCEEDED';

    const DATACLOUD_API_CLIENT_EXCEPTION = 'DATACLOUD_API_CLIENT_EXCEPTION';

    const DATACLOUD_API_SERVER_BUSY_EXCEPTION = 'DATACLOUD_API_SERVER_BUSY_EXCEPTION';

    const DATACLOUD_API_SERVER_EXCEPTION = 'DATACLOUD_API_SERVER_EXCEPTION';

    const DATACLOUD_API_UNAVAILABLE = 'DATACLOUD_API_UNAVAILABLE';

    const DUPLICATE_ARGUMENT_VALUE = 'DUPLICATE_ARGUMENT_VALUE';

    const DUPLICATE_VALUE = 'DUPLICATE_VALUE';

    const EMAIL_BATCH_SIZE_LIMIT_EXCEEDED = 'EMAIL_BATCH_SIZE_LIMIT_EXCEEDED';

    const EMAIL_TO_CASE_INVALID_ROUTING = 'EMAIL_TO_CASE_INVALID_ROUTING';

    const EMAIL_TO_CASE_LIMIT_EXCEEDED = 'EMAIL_TO_CASE_LIMIT_EXCEEDED';

    const EMAIL_TO_CASE_NOT_ENABLED = 'EMAIL_TO_CASE_NOT_ENABLED';

    const EXCEEDED_ID_LIMIT = 'EXCEEDED_ID_LIMIT';

    const EXCEEDED_LEAD_CONVERT_LIMIT = 'EXCEEDED_LEAD_CONVERT_LIMIT';

    const EXCEEDED_MAX_SIZE_REQUEST = 'EXCEEDED_MAX_SIZE_REQUEST';

    const EXCEEDED_MAX_TYPES_LIMIT = 'EXCEEDED_MAX_TYPES_LIMIT';

    const EXCEEDED_QUOTA = 'EXCEEDED_QUOTA';

    const FEED_NOT_ENABLED_FOR_OBJECT = 'FEED_NOT_ENABLED_FOR_OBJECT';

    const FUNCTIONALITY_NOT_ENABLED = 'FUNCTIONALITY_NOT_ENABLED';

    const FUNCTIONALITY_TEMPORARILY_UNAVAILABLE = 'FUNCTIONALITY_TEMPORARILY_UNAVAILABLE';

    const ILLEGAL_QUERY_PARAMETER_VALUE = 'ILLEGAL_QUERY_PARAMETER_VALUE';

    const INACTIVE_OWNER_OR_USER = 'INACTIVE_OWNER_OR_USER';

    const INACTIVE_PORTAL = 'INACTIVE_PORTAL';

    const INSUFFICIENT_ACCESS = 'INSUFFICIENT_ACCESS';

    const INVALID_ASSIGNMENT_RULE = 'INVALID_ASSIGNMENT_RULE';

    const INVALID_BATCH_SIZE = 'INVALID_BATCH_SIZE';

    const INVALID_CLIENT = 'INVALID_CLIENT';

    const INVALID_CROSS_REFERENCE_KEY = 'INVALID_CROSS_REFERENCE_KEY';

    const INVALID_FIELD = 'INVALID_FIELD';

    const INVALID_FILTER_LANGUAGE = 'INVALID_FILTER_LANGUAGE';

    const INVALID_FILTER_VALUE = 'INVALID_FILTER_VALUE';

    const INVALID_ID_FIELD = 'INVALID_ID_FIELD';

    const INVALID_LOCALE_LANGUAGE = 'INVALID_LOCALE_LANGUAGE';

    const INVALID_LOCATOR = 'INVALID_LOCATOR';

    const INVALID_LOGIN = 'INVALID_LOGIN';

    const INVALID_MULTIPART_REQUEST = 'INVALID_MULTIPART_REQUEST';

    const INVALID_NEW_PASSWORD = 'INVALID_NEW_PASSWORD';

    const INVALID_OPERATION = 'INVALID_OPERATION';

    const INVALID_OPERATION_WITH_EXPIRED_PASSWORD = 'INVALID_OPERATION_WITH_EXPIRED_PASSWORD';

    const INVALID_PAGING_OPTION = 'INVALID_PAGING_OPTION';

    const INVALID_QUERY_FILTER_OPERATOR = 'INVALID_QUERY_FILTER_OPERATOR';

    const INVALID_QUERY_LOCATOR = 'INVALID_QUERY_LOCATOR';

    const INVALID_QUERY_SCOPE = 'INVALID_QUERY_SCOPE';

    const INVALID_REPLICATION_DATE = 'INVALID_REPLICATION_DATE';

    const INVALID_SEARCH = 'INVALID_SEARCH';

    const INVALID_SEARCH_SCOPE = 'INVALID_SEARCH_SCOPE';

    const INVALID_SESSION_ID = 'INVALID_SESSION_ID';

    const INVALID_SOAP_HEADER = 'INVALID_SOAP_HEADER';

    const INVALID_SORT_OPTION = 'INVALID_SORT_OPTION';

    const INVALID_SSO_GATEWAY_URL = 'INVALID_SSO_GATEWAY_URL';

    const INVALID_TYPE = 'INVALID_TYPE';

    const INVALID_TYPE_FOR_OPERATION = 'INVALID_TYPE_FOR_OPERATION';

    const JIGSAW_IMPORT_LIMIT_EXCEEDED = 'JIGSAW_IMPORT_LIMIT_EXCEEDED';

    const JIGSAW_REQUEST_NOT_SUPPORTED = 'JIGSAW_REQUEST_NOT_SUPPORTED';

    const JSON_PARSER_ERROR = 'JSON_PARSER_ERROR';

    const LICENSING_UNKNOWN_ERROR = 'LICENSING_UNKNOWN_ERROR';

    const LIMIT_EXCEEDED = 'LIMIT_EXCEEDED';

    const LOGIN_CHALLENGE_ISSUED = 'LOGIN_CHALLENGE_ISSUED';

    const LOGIN_CHALLENGE_PENDING = 'LOGIN_CHALLENGE_PENDING';

    const LOGIN_DURING_RESTRICTED_DOMAIN = 'LOGIN_DURING_RESTRICTED_DOMAIN';

    const LOGIN_DURING_RESTRICTED_TIME = 'LOGIN_DURING_RESTRICTED_TIME';

    const LOGIN_MUST_USE_SECURITY_TOKEN = 'LOGIN_MUST_USE_SECURITY_TOKEN';

    const MALFORMED_ID = 'MALFORMED_ID';

    const MALFORMED_QUERY = 'MALFORMED_QUERY';

    const MALFORMED_SEARCH = 'MALFORMED_SEARCH';

    const MISSING_ARGUMENT = 'MISSING_ARGUMENT';

    const NOT_MODIFIED = 'NOT_MODIFIED';

    const NO_SOFTPHONE_LAYOUT = 'NO_SOFTPHONE_LAYOUT';

    const NUMBER_OUTSIDE_VALID_RANGE = 'NUMBER_OUTSIDE_VALID_RANGE';

    const OPERATION_TOO_LARGE = 'OPERATION_TOO_LARGE';

    const ORG_IN_MAINTENANCE = 'ORG_IN_MAINTENANCE';

    const ORG_IS_DOT_ORG = 'ORG_IS_DOT_ORG';

    const ORG_LOCKED = 'ORG_LOCKED';

    const ORG_NOT_OWNED_BY_INSTANCE = 'ORG_NOT_OWNED_BY_INSTANCE';

    const PASSWORD_LOCKOUT = 'PASSWORD_LOCKOUT';

    const PORTAL_NO_ACCESS = 'PORTAL_NO_ACCESS';

    const POST_BODY_PARSE_ERROR = 'POST_BODY_PARSE_ERROR';

    const QUERY_TIMEOUT = 'QUERY_TIMEOUT';

    const QUERY_TOO_COMPLICATED = 'QUERY_TOO_COMPLICATED';

    const REQUEST_LIMIT_EXCEEDED = 'REQUEST_LIMIT_EXCEEDED';

    const REQUEST_RUNNING_TOO_LONG = 'REQUEST_RUNNING_TOO_LONG';

    const SERVER_UNAVAILABLE = 'SERVER_UNAVAILABLE';

    const SOCIALCRM_FEEDSERVICE_API_CLIENT_EXCEPTION = 'SOCIALCRM_FEEDSERVICE_API_CLIENT_EXCEPTION';

    const SOCIALCRM_FEEDSERVICE_API_SERVER_EXCEPTION = 'SOCIALCRM_FEEDSERVICE_API_SERVER_EXCEPTION';

    const SOCIALCRM_FEEDSERVICE_API_UNAVAILABLE = 'SOCIALCRM_FEEDSERVICE_API_UNAVAILABLE';

    const SSO_SERVICE_DOWN = 'SSO_SERVICE_DOWN';

    const TOO_MANY_APEX_REQUESTS = 'TOO_MANY_APEX_REQUESTS';

    const TOO_MANY_RECIPIENTS = 'TOO_MANY_RECIPIENTS';

    const TRIAL_EXPIRED = 'TRIAL_EXPIRED';

    const UNKNOWN_ATTACHMENT_EXCEPTION = 'UNKNOWN_ATTACHMENT_EXCEPTION';

    const UNKNOWN_EXCEPTION = 'UNKNOWN_EXCEPTION';

    const UNSUPPORTED_API_VERSION = 'UNSUPPORTED_API_VERSION';

    const UNSUPPORTED_ATTACHMENT_ENCODING = 'UNSUPPORTED_ATTACHMENT_ENCODING';

    const UNSUPPORTED_CLIENT = 'UNSUPPORTED_CLIENT';

    const UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE';

    const XML_PARSER_ERROR = 'XML_PARSER_ERROR';
}
